Fix: Refresh Skin
qbcore-framework/qb-clothing pull request #67
Opened 2022-01-11 06:34 UTC by jay-fivem

might need a bit more testing, worked for me

2022-01-11 12:30 UTC, thekierandyer commented on client/main.lua
> +    	TriggerServerEvent("qb-clothing:loadPlayerSkin") -- LOADING PLAYER'S CLOTHES - Event 2
Could you remove this please? Unknown Event

2022-01-11 12:50 UTC, thekierandyer commented on client/main.lua
> +	local model = GetEntityModel(ped)
Might just be me being a defensive programmer, but could you add some logic in the event that GetEntityModel(ped) returns null please?

Eg set model to mp_m_freemode_01/mp_f_freemode_01

2022-01-11 13:29 UTC, thekierandyer requested changes
Other than the 2 changes i've listed, LGTM.

2022-01-11 13:30 UTC, thekierandyer commented on client/main.lua
> -    SetEntityHealth(PlayerPedId(), health)
I noticed when testing that if I /refreshskin'd whilst injured it set my health to 100 again. Could you re-add the SetEntityHealth stuff please (in the event is fine)

2022-03-09 19:56 UTC, ItsANoBrainer requested changes
This was my solution that properly saves Armor and Health. 
@jay-fivem Lets change it to this and then we can approve.
```lua
function RefreshSkin()
    local ped = PlayerPedId()
    local id = PlayerId()
    local maxhealth = GetPedMaxHealth(ped)
    local health = GetEntityHealth(ped)

    local maxarmour = GetPlayerMaxArmour(id)
    local armour = GetPedArmour(ped)

    local model = GetHashKey("mp_m_freemode_01")

    if PlayerData.charinfo.gender == 1 then -- Gender is ONE for FEMALE
        model = GetHashKey("mp_f_freemode_01") -- Female Model
    end 

    for _, v in pairs(GetGamePool('CObject')) do
        if IsEntityAttachedToEntity(ped, v) then
                SetEntityAsMissionEntity(v, true, true)
                DeleteObject(v)
                DeleteEntity(v)
        end
    end

    LoadPlayerModel(model)
    SetPlayerModel(id, model)
    SetModelAsNoLongerNeeded(model)

    Wait(1000) -- Safety Delay
    
    TriggerServerEvent("qb-clothes:loadPlayerSkin") -- Current Event
    TriggerServerEvent("qb-clothing:loadPlayerSkin") -- Legacy event?

    Wait(1000) -- Safety Delay

    ped = PlayerPedId()
    SetPedMaxHealth(ped, maxhealth)
    SetEntityHealth(ped, health)

    SetPlayerMaxArmour(id, maxarmour)
    SetPedArmour(ped, armour)
end
```

2022-04-07 01:28 UTC, closed without merging